on:
  push:
    branches: ['main']
    paths:
      - 'remote-templates-stg.yaml'
  pull_request:
   branches: ['main']
   paths:
     - 'remote-templates-stg.yaml'

env:
  BRANCH: feature/sync-prod
  COMMIT_MESSAGE: 'feat: sync prod via GHA'

jobs:
  sync-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ secrets.BACKSTAGE_APP_ID }}
          private_key: ${{ secrets.BACKSTAGE_APP_PEM }}
          
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b ${{ env.BRANCH }}-${{ github.run_id }}
          echo remote-templates-stg.yaml > remote-templates-prod.yaml
          git add .
          git commit -m "${{ env.COMMIT_MESSAGE }}"
          git push origin ${{ env.BRANCH }}-${{ github.run_id }}

      - name: Open Pull Request
        uses: actions/github-script@v6
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        with:
          script: |
            return await github.request('POST /repos/terwetr-org/slacks-remote-templates/pulls', {
              owner: terwetr-org
              repo: slacks-remote-templates,
              title: process.env.COMMIT_MESSAGE,
              body: 'PR via GHA',
              head: process.env.BRANCH,
              base: 'main',
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            })
      
